"""Scoped upgrade drain and receipt publication. Never modifies credentials or executes work."""
import hashlib
import json
import time
import urllib.error
import urllib.request
import uuid

class NoRedirect(urllib.request.HTTPRedirectHandler):
    def redirect_request(self,*args,**kwargs):
        return None

class MaintenanceLease:
    def __init__(self,config):
        self.config=config
        self.lease=hashlib.sha256(uuid.uuid4().bytes).hexdigest()
        self.active=False
        self.last_renewed=0.0
        self.opener=urllib.request.build_opener(NoRedirect())

    def _call(self,action,receipt=None):
        value={'action':action,'lease_id':self.lease,'ttl_seconds':300}
        if receipt is not None:
            allowed=('version','candidate_sha256','installed_sha256','state','phase','service_changed','pid','started_at','session','stable_seconds','samples','gateway_verified','all_lanes_verified','active_terminals','active_operations','error','rollback')
            # Error text is generated by the fixed updater, not command output.
            value['receipt']={k:v for k,v in receipt.items() if k in allowed}
        data=json.dumps(value).encode()
        for attempt in range(3):
            request=urllib.request.Request(self.config['gateway_url']+'/device/maintenance',data=data,
                headers={'Content-Type':'application/json','Accept':'application/json','User-Agent':'RemoteHosts-Updater/0.5.0','Authorization':'Bearer '+self.config['device_token']})
            try:
                with self.opener.open(request,timeout=10) as response:
                    payload=response.read(16385)
                    if len(payload)>16384: raise ValueError('oversize maintenance response')
                    return json.loads(payload)
            except urllib.error.HTTPError as error:
                code=error.code;error.close()
                if code not in (429,500,502,503,504) or attempt==2:
                    raise RuntimeError('maintenance_http_'+str(code)+'; inspect original lease; no credentials exposed') from None
            except (urllib.error.URLError,TimeoutError,OSError):
                if attempt==2:raise RuntimeError('maintenance_transport_unavailable; observe original lease') from None
            time.sleep(attempt+1)

    def acquire(self,record):
        self._call('acquire');self.active=True;self.last_renewed=time.monotonic()
        self.report(record)

    def report(self,record):
        if not self.active:return
        if time.monotonic()-self.last_renewed>30:
            self._call('acquire');self.last_renewed=time.monotonic()
        self._call('report',record)

    def close(self,record):
        if not self.active:return {'released':True,'was_acquired':False}
        try:
            self.report(record)
            self._call('release')
            self.active=False
            return {'released':True,'protocol':1}
        except Exception as error:
            return {'released':False,'protocol':1,'error_type':type(error).__name__,'recovery':'lease expires automatically; query device maintenance before new work','lease_ttl_seconds':300}
